using System.Data.Common;
using EFCore.NoLock.Core;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace EFCore.NoLock;

/// <summary>
/// An Entity Framework Core interceptor that injects <c>WITH (NOLOCK)</c> hints into SQL Server queries.
/// </summary>
/// <remarks>
/// <para>
/// <b>Deprecated.</b> Prefer <see cref="WithNoLockOptionsExtensions.UseNoLock(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)"/>,
/// which emits the hint during SQL generation so it is part of the SQL EF Core produces and appears in EF Core's own
/// command logs. This interceptor rewrites the SQL after EF Core captures the command text for logging, so the hint
/// never shows up in those logs (the SQL actually sent to the database still carries it).
/// </para>
/// <para>
/// This interceptor listens for database commands generated by EF Core. If a command contains the specific tag
/// added by the <c>WithNoLock()</c> extension method, it delegates to <see cref="NoLockSqlTransformer"/>
/// to modify the SQL syntax tree, appending the <c>WITH (NOLOCK)</c> table hint to all accessed tables.
/// </para>
/// <para>
/// <b>Performance Note:</b> The underlying transformer uses <see cref="Microsoft.SqlServer.TransactSql.ScriptDom"/> for safe SQL parsing
/// and includes an internal cache mechanism to prevent re-parsing identical queries, ensuring minimal performance overhead.
/// </para>
/// </remarks>
[Obsolete("Use optionsBuilder.UseNoLock() instead. The generator-based approach emits WITH (NOLOCK) during SQL generation, so it shows up in EF Core's command logs; this interceptor's hint does not.")]
public class WithNoLockInterceptor : DbCommandInterceptor
{
    /// <summary>
    /// Intercepts a reader command before execution and injects the <c>WITH (NOLOCK)</c> hint when the
    /// NOLOCK tag is present. This is the point at which the generated SQL is available on the command.
    /// </summary>
    public override InterceptionResult<DbDataReader> ReaderExecuting(
        DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result)
    {
        NoLockSqlTransformer.ApplyNoLock(command);
        return base.ReaderExecuting(command, eventData, result);
    }

    /// <summary>
    /// Asynchronous counterpart of <see cref="ReaderExecuting"/> (e.g. <c>ToListAsync</c>).
    /// </summary>
    public override ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
        DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result,
        CancellationToken cancellationToken = default)
    {
        NoLockSqlTransformer.ApplyNoLock(command);
        return base.ReaderExecutingAsync(command, eventData, result, cancellationToken);
    }
}